**IMPORTING CSV FILES**

In [1]:
import pandas as pd

In [14]:
df=pd.read_csv('/content/college_student_placement_dataset.csv')

In [3]:
df.describe()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,99.471800,7.535673,7.532379,5.546400,4.970900,5.561800,2.513400
std,15.053101,1.447519,1.470141,2.873477,3.160103,2.900866,1.715959
min,41.000000,5.000000,4.540000,1.000000,0.000000,1.000000,0.000000
25%,89.000000,6.290000,6.290000,3.000000,2.000000,3.000000,1.000000
50%,99.000000,7.560000,7.550000,6.000000,5.000000,6.000000,3.000000
75%,110.000000,8.790000,8.770000,8.000000,8.000000,8.000000,4.000000
max,158.000000,10.000000,10.460000,10.000000,10.000000,10.000000,5.000000

In [4]:
df.head()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No

In [5]:
df.head(18)

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No
5,CLG0015,96,5.26,5.32,7,No,5,8,0,No
6,CLG0071,123,6.68,6.58,5,No,7,8,2,Yes
7,CLG0096,111,8.77,8.76,7,No,3,1,2,Yes
8,CLG0097,92,6.47,6.33,9,No,7,8,5,No
9,CLG0057,108,8.82,8.60,4,No,5,9,1,No
10,CLG0063,93,8.73,8.90,2,Yes,5,6,0,No
11,CLG0077,93,6.23,6.51,8,No,5,7,4,No
12,CLG0064,103,8.64,9.01,7,Yes,8,6,1,No
13,CLG0017,71,8.74,8.40,6,No,0,5,2,No
14,CLG0053,74,6.99,7.31,7,No,0,1,2,No
15,CLG0040,91,6.05,5.80,3,No,4,2,3,No
16,CLG0070,84,7.61,7.54,6,No,0,10,0,No
17,CLG0050,104,9.61,10.01,10,Yes,9,2,4,No

In [6]:
df.tail()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
9995,CLG0021,119,8.41,8.29,4,No,1,8,0,Yes
9996,CLG0098,70,9.25,9.34,7,No,0,7,2,No
9997,CLG0066,89,6.08,6.25,3,Yes,3,9,5,No
9998,CLG0045,107,8.77,8.92,3,No,7,5,1,No
9999,CLG0060,109,9.41,9.77,8,No,3,5,5,No

In [7]:
df.tail(18)

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
9982,CLG0043,107,5.30,5.26,1,Yes,5,9,3,No
9983,CLG0014,103,7.36,7.35,5,Yes,2,5,4,No
9984,CLG0089,82,7.58,7.56,1,No,10,10,1,No
9985,CLG0052,94,9.27,9.37,6,No,10,2,0,No
9986,CLG0027,94,8.66,8.19,8,Yes,2,6,1,No
9987,CLG0093,73,5.40,5.89,7,Yes,7,1,1,No
9988,CLG0052,85,6.05,6.27,1,No,3,10,1,No
9989,CLG0001,88,6.56,6.49,8,Yes,9,10,2,No
9990,CLG0046,121,5.58,5.27,9,No,7,3,2,No
9991,CLG0005,102,7.28,6.86,10,Yes,9,3,1,No
9992,CLG0062,109,9.92,10.09,2,Yes,5,10,3,Yes
9993,CLG0056,77,7.57,7.39,1,Yes,2,6,3,No
9994,CLG0064,117,8.71,8.44,6,No,9,4,4,Yes
9995,CLG0021,119,8.41,8.29,4,No,1,8,0,Yes
9996,CLG0098,70,9.25,9.34,7,No,0,7,2,No
9997,CLG0066,89,6.08,6.25,3,Yes,3,9,5,No
9998,CLG0045,107,8.77,8.92,3,No,7,5,1,No
9999,CLG0060,109,9.41,9.77,8,No,3,5,5,No

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  object
 1   IQ                      10000 non-null  int64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  int64
 5   Internship_Experience   10000 non-null  object
 6   Extra_Curricular_Score  10000 non-null  int64
 7   Communication_Skills    10000 non-null  int64
 8   Projects_Completed      10000 non-null  int64
 9   Placement               10000 non-null  object
dtypes: float64(2), int64(5), object(3)
memory usage: 781.4+ KB

In [10]:
df.columns

Index(['College_ID', 'IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance',
       'Internship_Experience', 'Extra_Curricular_Score',
       'Communication_Skills', 'Projects_Completed', 'Placement'],
      dtype='object')

**IMPORTING TEXT FILES**

In [11]:
import pandas as pd

In [16]:
df1=pd.read_csv('/content/business_1.txt',delimiter='\t')

In [17]:
df1.describe()

                           Lufthansa flies back to profit
count                                                   2
unique                                                  2
top     German airline Lufthansa has returned to profi...
freq                                                    1

In [18]:
df1.head()

                      Lufthansa flies back to profit
0  German airline Lufthansa has returned to profi...
1  In a preliminary report, the airline announced...

In [19]:
df1.tail()

                      Lufthansa flies back to profit
0  German airline Lufthansa has returned to profi...
1  In a preliminary report, the airline announced...

In [21]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Lufthansa flies back to profit  2 non-null      object
dtypes: object(1)
memory usage: 148.0+ bytes

In [22]:
df1.columns

Index(['Lufthansa flies back to profit'], dtype='object')

**IMPORTING EXCEL FILES**

In [23]:
import pandas as pd

In [30]:
df2=pd.read_excel('/content/Cola.xlsx')

In [31]:
df2.describe()

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
count,3,97,82,82,82,82,82,82,90,92,93,93
unique,3,90,77,77,77,77,77,78,79,78,87,86
top,Profit & Loss statement,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,0,0,FY '17,FY '18
freq,1,3,3,3,3,3,3,3,6,8,3,3

In [32]:
df2.head()

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Profit & Loss statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,FY '15,FY '16,FY '17,FY '18
3,NaN,NET OPERATING REVENUES,30990,35119,46542,48017,46854,45998,44294,41863,35410,31856
4,NaN,Cost of goods sold,11088,12693,18215,19053,18421,17889,17482,16465,13255,11770

In [33]:
df2.head(18)

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Profit & Loss statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,FY '15,FY '16,FY '17,FY '18
3,NaN,NET OPERATING REVENUES,30990,35119,46542,48017,46854,45998,44294,41863,35410,31856
4,NaN,Cost of goods sold,11088,12693,18215,19053,18421,17889,17482,16465,13255,11770
5,NaN,Gross Profit,19902,22426,28327,28964,28433,28109,26812,25398,22155,20086
6,NaN,"Selling, general and administrative expenses",11358,13194,17422,17738,17310,17218,16427,15262,12654,10307
7,NaN,Other operating charges,313,819,732,447,895,1183,1657,1510,1902,1079
8,NaN,Operating Income,8231,8413,10173,10779,10228,9708,8728,8626,7599,8700
9,NaN,Interest income,249,317,483,471,534,594,613,642,677,682
10,NaN,Interest expense,355,733,417,397,463,483,856,733,841,919
11,NaN,Equity income (loss) - net,781,1025,690,819,602,769,489,835,1071,1008
12,NaN,Other income (loss) - net,40,5185,529,137,576,-1263,631,-1234,-1764,-1121
13,NaN,Income before income taxes,8946,14207,11458,11809,11477,9325,9605,8136,6742,8350
14,NaN,Income taxes,2040,2370,2812,2723,2851,2201,2239,1586,5560,1623
15,NaN,CONSOLIDATED NET INCOME,6906,11837,8646,9086,8626,7124,7366,6550,1283,6476
16,NaN,Less: Net income attributable to noncontrollin...,82,50,62,67,42,26,15,23,35,42
17,NaN,Net income from continuing operations,NaN,NaN,NaN,NaN,NaN,NaN,7366,6550,1182,6727

In [34]:
df2.tail()

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
98,NaN,Effect of exchange rate changes on cash and ca...,576,-166,-430,-255,-611,-934,-878,-6,241,-262
99,NaN,Cash Provided by (Used in) Investing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-58,-421
100,NaN,Cash Provided by (Used in) Financing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-38,205
101,NaN,Net Cash Provided by (Used in) Discontinued Op...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,15,91
102,NaN,Net increase (decrease) during the year,2320,1496,4286,-4361,1972,-1456,-1649,1246,-2477,2945

In [35]:
df2.tail(18)

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
85,NaN,"Proceeds from disposals of businesses, equity ...",240,972,398,20,872,148,565,1035,3821,1362
86,NaN,"Purchases of property, plant and equipment",-1993,-2215,-2920,-2780,-2550,-2406,-2553,-2262,-1675,-1347
87,NaN,"Proceeds from disposals of property, plant and...",104,134,101,143,111,223,85,150,104,245
88,NaN,Other investing activities,-48,-106,-145,-268,-303,-268,-40,-209,-93,-60
89,NaN,Net cash provided by (used in) investing activ...,-4149,-4405,-2524,-11404,-4214,-7506,-6186,-999,-2254,6348
90,NaN,Issuances of debt,14689,15251,27495,42791,43425,41674,40434,27281,29857,27339
91,NaN,Payments of debt,-12326,-13403,-22530,-38573,-38714,-36962,-37738,-25615,-28768,-30568
92,NaN,Issuances of stock,664,1666,1569,1489,1328,1532,1245,1434,1595,1476
93,NaN,Purchases of stock for treasury,-1518,-2961,-4513,-4559,-4832,-4162,-3564,-3681,-3682,-1912
94,NaN,Dividends,-3800,-4068,-4300,-4595,-4969,-5350,-5741,-6043,-6320,-6644
95,NaN,Other financing activities,-2,50,45,100,17,-363,251,79,-91,-243
96,NaN,Net cash provided by (used in) financing activ...,-2293,-3465,-2234,-3347,-3745,-3631,-5113,-6545,-7409,-10552
97,NaN,Cash Provided by (Used in) Operating Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,111,307
98,NaN,Effect of exchange rate changes on cash and ca...,576,-166,-430,-255,-611,-934,-878,-6,241,-262
99,NaN,Cash Provided by (Used in) Investing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-58,-421
100,NaN,Cash Provided by (Used in) Financing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-38,205
101,NaN,Net Cash Provided by (Used in) Discontinued Op...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,15,91
102,NaN,Net increase (decrease) during the year,2320,1496,4286,-4361,1972,-1456,-1649,1246,-2477,2945

In [36]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Data provided by SimFin  3 non-null      object
 1   Unnamed: 1               97 non-null     object
 2   Unnamed: 2               82 non-null     object
 3   Unnamed: 3               82 non-null     object
 4   Unnamed: 4               82 non-null     object
 5   Unnamed: 5               82 non-null     object
 6   Unnamed: 6               82 non-null     object
 7   Unnamed: 7               82 non-null     object
 8   Unnamed: 8               90 non-null     object
 9   Unnamed: 9               92 non-null     object
 10  Unnamed: 10              93 non-null     object
 11  Unnamed: 11              93 non-null     object
dtypes: object(12)
memory usage: 9.8+ KB

In [37]:
df2.columns

Index(['Data provided by SimFin', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11'],
      dtype='object')